### ISSUE TITLE
Is it possible for infix command to store an option value to an Emacs variable?

### ISSUE THREAD

**Issue by YorkZ** [magit/transient#100]
Currently, what I'm doing is to define an infix command with `transient-define-argument `
```
(transient-define-argument my-application:--target ()
  :description "target device name"
  :class 'transient-option
  :shortarg "-t"
  :argument "--target="
  :choices '("device-1" "device-1" "device-3"))
```
This is inconvenience because what the suffix command get is a string, e.g., `--target=device-1`, and the suffix command would have to parse this string to get the value `device-1`.

Is it possible to have this infix command storing the value `device-1` into an Emacs variable, e.g. `device-name` so that the suffix command can simply get the value `device-1` from the variable `device-name` without having to parse the string `--target=device-1`?

**Comment by tarsius** [comment]
You can use the `transient-lisp-variable` class for that. I added that about two months ago.

Example:

```elisp
(transient-define-infix guix-set-current-profile-from-popup ()
  "Set `guix-current-profile' from a popup buffer."
  :class 'transient-lisp-variable
  :variable 'guix-current-profile
  :reader (lambda (_prompt default _history)
	    (guix-read-package-profile default)))
```

**Comment by YorkZ** [comment]
Thanks a lot @tarsius, this is cool. However, I think to make it really useful, it would be better to improve it by:

1. Support saving the value across Emacs sessions by pressing `C-x C-s`.
2. Support the `:choices` keyword

Not sure if `transient` can already do this in some way?

**Comment by tarsius** [comment]
> Support saving the value across Emacs sessions by pressing `C-x C-s`.

In most cases it makes more sense to save variables at the same time as when they are being set.

Consider how Magit saves Git variables right after it has prompted you for the new value. Of course in this case there is no difference between setting and saving a value because the value has to be set outside of Emacs. Still I think one should not think of the value of a variable as part of the value of the transient.

How exactly a variable should be saved is going to differ a great deal between packages and even just different variables, so I have chosen the smallest common denominator, `set`.  The idea was that users would implement their own class derived from `transient-lisp-variable` and implement their preferred way of saving.

But I have just taught `transient-lisp-variable` to use an alternative function, specified using the new `set-value` slot.

``` emacs-lisp
(cl-defmethod transient-infix-set ((obj transient-lisp-variable) value)
  (funcall (oref obj set-value)
           (oref obj variable)
           (oset obj value value)))
```

If you want to use e.g. `custom-save-variable` for many variables, then it may be inconvenient having to specify `set-value` for each one of them, in which case you will have to implement your own derived class, which implements `transient-infix-set`.

> Support the `:choices` keyword

While there are many ways of saving a lisp variable, there are infinite forms the values can take.  I therefore don't think it makes sense to optimize for certain types of values.

So to get this you must implement your own class, which implements a few generic functions. For inspiration, grep `transient.el` for `choices`.  You will probably end up implementing `transient-infix-read`, combining things done in the methods of `transient-infix` and `transient-switches`.  And from the `transient-format-value` of `transient-switches` you will have to learn as well.

**Comment by tarsius** [comment]
> Support saving the value across Emacs sessions by pressing `C-x C-s`.

In most cases it makes more sense to save variables at the same time as when they are being set.

Consider how Magit saves Git variables right after it has prompted you for the new value. Of course in this case there is no difference between setting and saving a value because the value has to be set outside of Emacs. Still I think one should not think of the value of a variable as part of the value of the transient.

How exactly a variable should be saved is going to differ a great deal between packages and even just different variables, so I have chosen the smallest common denominator, `set`.  The idea was that users would implement their own class derived from `transient-lisp-variable` and implement their preferred way of saving.

But I have just taught `transient-lisp-variable` to use an alternative function, specified using the new `set-value` slot.

``` emacs-lisp
(cl-defmethod transient-infix-set ((obj transient-lisp-variable) value)
  (funcall (oref obj set-value)
           (oref obj variable)
           (oset obj value value)))
```

If you want to use e.g. `custom-save-variable` for many variables, then it may be inconvenient having to specify `set-value` for each one of them, in which case you will have to implement your own derived class, which implements `transient-infix-set`.

> Support the `:choices` keyword

While there are many ways of saving a lisp variable, there are infinite forms the values can take.  I therefore don't think it makes sense to optimize for certain types of values.

So to get this you must implement your own class, which implements a few generic functions. For inspiration, grep `transient.el` for `choices`.  You will probably end up implementing `transient-infix-read`, combining things done in the methods of `transient-infix` and `transient-switches`.  And from the `transient-format-value` of `transient-switches` you will have to learn as well.
