### ISSUE TITLE
TAB vs <tab> in org-mode

### ISSUE THREAD

**Issue by sheijk** [magit/transient#107]
Transient menus cannot handle both the physical tab key and `C-i` if called from inside org-mode buffers. If called from buffers with other major-modes things work as expected.

Starting `emacs -q` and evaluating the following code reproduces the problem (assuming transient has been installed using package.el):

```lisp
(setq package-user-dir "~/emacs/elpa")
(package-initialize)

(require 'transient)

(transient-define-prefix shk-repro-transient-tab ()
  "Demonstrate issue with tab binding in org-mode"
  ["Tab"
   ;; ("<tab>" "works with tab key" (lambda () (interactive) (message "tab")))
   ("TAB" "works with control i" (lambda () (interactive) (message "control i")))
   ])

(switch-to-buffer "demo.org")
(org-mode)
(shk-repro-transient-tab)
```

Now pressing the physical tab key will show "Unbound suffix: ‘<tab>’ (Use ‘C-g’ to abort, ‘?’ for help) [org-cycle]". If the call `(org-mode)` gets removed it will work as expected.

This seems to be related to Emacs' key translation. `C-h k TAB` shows me this in most major-modes `TAB (translated from <tab>) runs the command [...]` while in org-mode I see `<tab> runs the command [...]`.

Versions:
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28
transient 20210103.1546
Magit 20210105.1030, Git 2.29.2, Emacs 27.1, gnu/linux
Manjaro Linux (rolling release but up-to-date)

**Comment by tarsius** [comment]
Indeed, transient does not perform the usual key translation. So if you want to bind the physical tab key, then you have to actually bind that instead of `C-i`. You can bind `C-i` to something else if you wish. (Or even the same command, but that would be ugly due to the resulting visual duplication.)

The question is whether this has to be "fixed" in transient. Most keyboards do have a dedicated tab key and that's what users press when they want to invoke the tab action, not Control+i. And even users who don't usually do that can see in the interface that they are supposed to press `<tab>` in this case.

**Comment by sheijk** [comment]
Yes, the source of the problem is org-mode's approach to bind both instead of keeping the remapping. But I think it's also a matter of robustness and consistency - nearly everywhere else in Emacs tab key and C-i are treated as equivalent, similarly to RET and C-m.

Having two bindings displayed is a work-around, although a sub-optimal one. Maybe transient could get a keyword to make a binding invisible (and only show it when showing extended commands?) or to have two keys? That would also be useful for transients with a lot bindings (for example allowing to move around using default bindings like M-f/M-b while the menu is open etc.)

**Comment by tarsius** [comment]
> nearly everywhere else in Emacs tab key and C-i are treated as equivalent, similarly to RET and C-m.

I know, and I consider it an extremely unfortunate historic accident. I use `C-{jikl}` instead of `C-{bpnf}` for basic navigation and end up having to fix just about every other keymap because of this.

> Having two bindings displayed is a work-around, although a sub-optimal one.

Not really. These menus are supposed to display all the bindings and `<tab>` and `C-i` are two different bindings and if you want both then that makes two bindings/menu-entries.

I don't understand why you want `C-i` to be usable in the first place, and I don't think that's just because of how I want to use that key combination myself.

The entry in the menu says `<tab>`--why should `C-i` do the same thing? "Nobody" actually presses that key combination to do "the tab thing" and those that do also understand that `<tab>` is being redirected to `C-i` and (sadly, in my opinion) not the other way around and that when they see `<tab>` then that means "`tab` but not `C-i`".

And speaking of "robustness and consistency", I don't think such "key binding aliases" are really a shining example of that, "surprising and hard to undo" seem more fitting. :grin:

I don't want to implement support for this.
