### ISSUE TITLE
Popup gets stuck after setting branch upstream

### ISSUE THREAD

**Issue by thegeorgeous** [magit/transient#11]
## Steps to reproduce:
- Open the branch popup
- Press `u` to set the upstream branch
- Select the branch in the prompt
- The branch popup stops responding to `C-g` after the upstream branch is set

## Expected behaviour:
Branch popup should close

In fact, Emacs stops responding to all keys except `?` which displays the help text. I get the Unbound suffix messages for all the other keys.

**Comment by tarsius** [comment]
That works for me. At what point *exactly* do things start to go wrong? Please explain what you do and see happening in detail. For example, is the value unset before you start or are you changing the value? Do you get a prompt asking you to select a branch? Do you get `Unbound suffix ...` messages or not? ...

**Comment by thegeorgeous** [comment]
@tarsius, I've updated the description

**Comment by tarsius** [comment]
How did you install transient?
Do you use some third-party completion framework?

**Comment by thegeorgeous** [comment]
I use Spacemacs with the git layer enabled. I added forge to `dotspacemacs-additional-packages '()`.

**Comment by tarsius** [comment]
I assume that means you are using Evil, including `evil-magit`. Try updating the `evil-magit` package. Also look at recent issues of that package, there might be something relevant there.

Can you reproduce this if you disable Evil bindings?

**Comment by thegeorgeous** [comment]
@tarsius, don't know if this helps, but this issue doesn't appear if I uninstall forge and I don't use the fuzzy search for upstream branches.

**Comment by tarsius** [comment]
> don't know if this helps

I am afraid it mostly confuses me.

On the plus side this might mean that the issue was caused by the use of an outdated version of Forge.  Maybe Forge would work if you installed the latest version.  Or rather any version that assumes that Magit uses Transient.  Older versions assumed it uses Magit-Popup.  On the other hand I switched back and forth between Magit's `master` branch and the branch I used to develop support for Transient and I never had this issue, so maybe not.

> but this issue doesn't appear if I uninstall forge and I don't use the fuzzy search for upstream branches.

It is unclear to me what "and" means here.  Are you saying that it works provided you (1) uninstall forge AND (2) refrain from using fuzzy search?  Or are you just adding the additional piece of information that you do not use fuzzy search (neither before nor after the issue emerged)?

**Comment by tarsius** [comment]
If it is the latter, then please provide more information about what kind of "fuzzy search" you are referring to. There are many packages that implement "fuzzy search" and I need to know which one you are using in order to try to reproduce the issue.

**Comment by tarsius** [comment]
Without more information I cannot be of any more help. It also appears other users are not affected.
