### ISSUE TITLE
`unread-command-events` not being read (or maybe transient delayed?)

### ISSUE THREAD

**Issue by GuiltyDolphin** [magit/transient#117]
I'm working on [a project](https://github.com/GuiltyDolphin/org-gtd/tree/dev) that is using transient for some user interface work (there's lots of wrappers around transient there, so if there's anything you want to use, just let me know and I can do a PR). In testing the user interfaces, I noticed that I wasn't able to emulate keypresses in Emacs' batch mode for transient. For example:

Firstly, evaluate the following code, then run `(transient--bug-run)`, you'll notice that you get messages informing you that `transient--bug-var` has the value `0` (twice), but if you run this again you'll notice that the value has increased (this is because the messages are getting output before `transient--bug` has finished, somehow):

```
(defvar transient--bug-var 0)

(transient-define-suffix transient--bug-suffix ()
  (interactive)
  (setq transient--bug-var (+ 1 transient--bug-var)))

(transient-define-prefix transient--bug ()
  "Var doesn't get modified."
  [("t" transient--bug-suffix)])

(defun transient--bug-run ()
  (message "Transient bug var: %s" transient--bug-var)
  (setq unread-command-events (listify-key-sequence "t"))
  (transient--bug)
  (message "Transient bug var: %s" transient--bug-var))
``` 

Now put the above code in a file called `transient-bug.el`, and assuming you are in the same directory and the path to your `transient.el` file is `TRANSIENT_PATH`, run:

```
emacs -Q --batch -l TRANSIENT_PATH -l transient-bug.el --eval='(progn (transient--bug-run) (transient--bug-run))'
```

You'll notice that you get the output:

```
Transient bug var: 0
Transient bug var: 0
Transient bug var: 0
Transient bug var: 0
```

So this means that the `unread-command-events` is getting treated weirdly somewhere along the lines. I thought this might be something to do with Emacs' batch mode preventing the `unread-command-events` from being read, but if you run `emacs -Q --batch --eval='(progn (setq unread-command-events (listify-key-sequence "t")) (message "%s" (char-to-string (read-key))))'`, you'll notice the output is `t`, as expected.

After some further exploration, I found that this issue also occurs when running without `--batch`, it seems that somehow the transients are occurring out of sequence with other code - if you add debug messages to the suffix defined above, for example, you'll notice that they won't be printed unless you run the transient directly (and messages before/after the call to the transient are often printed before messages inside the transient).

Any thoughts on this? Is this a bug in transient, or am I perhaps misunderstanding the order of execution here? I feel like one ought to be able to just set `unread-command-events`, then run a transient and have this accept the keys from `unread-command-events` in the same manner that e.g., `read-key` would - but this doesn't appear to be happening consistently, and means that transients can't be tested well via e.g., `ert`.

**Comment by tarsius** [comment]
1. You most likely should just invoke the suffix directly.

   ```elisp
   (call-interactively 'the-suffix)
     or better
   (the-suffix (transient-args 'the-prefix))
   ```
   
2. The behavior you observe has nothing to do with transient.

   You would get similar behavior if you removed the transient specific bits.
   
   Setting `unread-command-events` has no effect until the next time
   input is read.  If you explicitly `read-key`, then input is read.
   Otherwise input is not read until the next time we return to the
   command loop, which by definition cannot happen while a command is
   still running.
   
   I am guessing that the command loop has not been started yet at the
   time when forms that were provided using `--eval` are being processes.

**Comment by GuiltyDolphin** [comment]
Okay, so you'd recommend (1) for invoking transients during `ert` tests?

I do find it strange how sometimes setting `unread-command-events` works for getting transient to read the events, but in most cases doesn't seem to - the transient never invokes its suffixes based on the keys if it isn't part of an actual command call from the user.

What would be your recommendation in terms of spawning transients that you can keypresses to in a synchronous manner (currently as soon as a transient is run, it seems to run asynchronously and control passes to the next part of a body)? I'm trying the forms you suggested in (1) but `(transient-suffix-object)` is just returning `nil` (versus when invoked via a prefix, when it returns a value) - is this to be expected? It means that I can't check values specific to the instance of the suffix.

**Comment by tarsius** [comment]
> Okay, so you'd recommend (1) for invoking transients during `ert` tests?

Yes. (I am guessing those tests are supposed to test the invoked transients.)

> I do find it strange how sometimes setting `unread-command-events` works for getting transient to read the events, but in most cases doesn't seem to - the transient never invokes its suffixes based on the keys if it isn't part of an actual command call from the user.

Transient *never* "reads the events". You just think it sometimes does because you are using a wrong mental modal. When one in invokes a transient prefix, then that does NOT enter some recursive edit. (It's predecessor `magit-popup` did just that, so it is not surprising that you assume `transient` does that, it would be a reasonable approach.)

What happens instead is this: You invoke a transient prefix command. Then that command creates a buffer that displays the available suffixes. It also puts some keymaps and hooks into effect. Then it returns and is done. The prefix command is not running anymore. At this point (when no command is running) Emacs returns to the command loop, where it waits for new events. New events arrive, usually because the user presses some keys. But the command loop also looks at `unread-command-events`, if that is non-nil, then it treats those events more or less like user input.

**Comment by GuiltyDolphin** [comment]
Hmm okay - I need to think about how to make use of the keymaps/hooks to get the testing behaviour. I'll let you know if I figure it out, or encounter further difficulty. Thanks!

**Comment by tarsius** [comment]
Alright. Meanwhile I close this because there probably isn't an issue in Transient. You can of course continue to comment here and if the facts change, then we can also reopen it.
