### ISSUE TITLE
Feature request: Support Edebug

### ISSUE THREAD

**Issue by basil-conto** [magit/transient#19]
[I'm submitting this feature request further to the discussion in magit/magit#3761.]

Transients started during an Edebug session (e.g. when stepping through a `define-transient-command`) currently override all Edebug key bindings, making it nearly impossible to either continue edebugging or to quit either Edebug or Transient.

The only way I can currently recover from such a scenario is via <kbd>M-:</kbd>`(error "")`<kbd>RET</kbd>.

It would be nice if Transient were less intrusive and supported Edebug, given the feature's importance.

Thanks!

**Comment by basil-conto** [comment]
> The only way I can currently recover from such a scenario is via M-:`(error "")`RET.

Sorry, this is not actually true. I'm not sure how I managed to do that last time, and even after signalling the error that time, Emacs remained completely unusable (global key bindings remained clobbered) and I had to kill the process.

**Comment by tarsius** [comment]
I don't actually use edebug, and when I just tried to use it in order to reproduce the issue it turned out that I cannot even figure out how to use it. Maybe that's the reason I don't use it. ;-)

I tried by typing `C-u C-M-x ` on the definition of `magit-log-head`, which resulted in the message `Edebug: magit-log-head`, which I assume means that the function was successfully instrumented. This is a completely normal command, while it usually is invoked as a suffix of `magit-log`, but it can also be invoked using `M-x magit-log-head RET`. I did that and the log was displayed. No buffer popped edebug or backtrace or whatever buffer up and I did not get the impression that the execution was somehow slowed down.

What did I do wrong? Please provide step by step instructions on how to edbug even just such a plain old command.

----

By the way, I doubt that edebug will be useful to debug transient. Maybe to debug bugs in suffix commands, that don't have anything to do with the transient functionality, but not when the bug is in transient itself or in how the command uses the transient features.

Transient is pretty complex, involving transient maps, pre and post command hooks, a bunch of other hooks etc. The flow isn't linear. While I was writing transient there were lots of bugs that concerned the flow of control. I think I have fixed them all, except for those that involve another package that also messes with the flow of things. If such a bug arises, then enabling a third package, edebug, which *also* messes with that, won't make it easier to debug the issue. It's much more likely that the interaction of the three packages lead to completely different incorrect behavior than the incorrect behavior involving two packages that we wanted to debug.

I have added debug statements to critical transient functions, which can be enabled by setting `transient--debug` to `t`. These statements have proven very useful in debugging flow control bugs.

----

So I believe the best I can to with regards to edebug is to detect when it is activated and deactivate it to prevent bad interaction. In order to do that I first have to learn (with your help) how to actually activate edebug.

**Comment by basil-conto** [comment]
Sorry, I was away last week; I'll get back to this before the end of this week.

**Comment by basil-conto** [comment]
> I tried by typing `C-u C-M-x` on the definition of `magit-log-head`, which resulted in the message `Edebug: magit-log-head`, which I assume means that the function was successfully instrumented. This is a completely normal command. While it usually is invoked as a suffix of `magit-log`, it can also be invoked using `M-x magit-log-head RET`. I did that and the log was displayed. No edebug, backtrace or whatever buffer popped up and I did not get the impression that the execution was somehow slowed down.

> What did I do wrong? Please provide step by step instructions on how to edbug even just such a plain old command.

1. `make emacs-Q`
2. <kbd>M-x</kbd>`find-function`<kbd>RET</kbd>`magit-log-head`<kbd>RET</kbd>
3. <kbd>C-u</kbd><kbd>C-M-x</kbd>
4. <kbd>M-x</kbd>`magit-log-head`<kbd>RET</kbd>

Edebug should now be activated in "step mode", with point on the opening parenthesis of the `interactive` spec of `magit-log-head`:

![magit-log-head](https://user-images.githubusercontent.com/9121222/54431214-b9e61c80-471d-11e9-8533-142692787f0f.png)

Repeatedly typing <kbd>SPC</kbd> should eventually step through the whole command. Alternatively, <kbd>q</kbd> will quit from the call to `magit-log-head`, or <kbd>g</kbd> will continue execution until the next "break".

If this does not work for you then there's probably either something wrong with your Emacs installation, or a bug in Emacs.

---

I understand and appreciate your concerns with Edebug; perhaps it is not the right tool for Transient, which indeed seems like a very intrusive feature, in that it hooks into some very central aspects of Emacs' command loop. With maturity, the need to debug it will likely lessen. Feel free to close/resolve this issue as you see fit, and thanks for your work on this.

**Comment by tarsius** [comment]
Thanks! It seems I just didn't notice the little arrow in the fringe.

**Comment by tarsius** [comment]
Edebug works in some cases, e.g. stepping through `magit-log-head` even when it is invoked from the log transient. I think it would be too difficult to differentiate uses of Edebug that will work just fine from those that will blow up, so I am just leaving things as is.

**Comment by Silex** [comment]
@tarsius: just FYI, when in a `edebug` session `transient-args` returns nil. No time to find out why, but thought you'd like to know.

**Comment by marcbowes** [comment]
I ran into an issue where I enabled edebug not knowing it would trigger while a transient was active, then I had to pkill Emacs.

**Comment by alphapapa** [comment]
@marcbowes You can often interrupt Emacs with `pkill -SIGUSR2 emacs` when it seems to be frozen.

**Comment by marcbowes** [comment]
Emacs doesn't freeze, I just can't do anything. So for example if I press C-g, then transient reports "unknown suffix C-g". Same with almost anything I can think of, including using the mouse to select EDebug -> Quit.

**Comment by jdtsmith** [comment]
How about a keybinding while the transient is active which unloads the transient keymap?  Then edebug has a chance to proceed as normal.  I was trying to use edebug not to debug transient, but to understand it better [1].  I doubt this will be a rare occurrence for package coders trying to implement transient, so taking over the keyboard so completely as to prevent even _Menu_ commands from working will result in many unrecoverable Emacs sessions and sad programmers.   

In fact, I found I could _suspend_ transient with `C-x z` and then edebug worked as expected.  

[1] For example, I'm trying to see if a `transient-option` can be set to have a completable and limited set of options to fill in, e.g.:

```elisp 
("f" "Fruit" "fruit=" :choices '("apple" "banana" "pear"))
```
I see `:choices`, but haven't found a way to activate them, nor to have any completing during option filling.  So I thought to step through `transient-infix-read ((obj transient-infix))`.

**Comment by tarsius** [comment]
Okay, I have bumped this up on my todo list.

**Comment by tarsius** [comment]
> How about a keybinding while the transient is active which unloads the transient keymap?

Pressing `ESC` three times *should* already quit the transient in hairy cases.

**Comment by tarsius** [comment]
Should work now.
