### ISSUE TITLE
Title: keyboard access broken?

### ISSUE THREAD

**Issue by tvraman** [magit/transient#197]
Description: Moving through transient options works (emacs Git@HEAD)
but pressing enter on the current selection throws an invalid binding
error; this has again made transient very difficult to use from the
keyboard alone and has broken the experience in emacspeak that we
created together a few months ago.

**Comment by tarsius** [comment]
Hot fix:

```
(define-key map (kbd "RET") #'transient-push-button)
```

I'll have to look in more detail into what went wrong but am a bit busy right now.

**Comment by tarsius** [comment]
I meant:

```
(define-key transient-popup-navigation-map (kbd "RET") #'transient-push-button)
```

**Comment by tvraman** [comment]
thanks, will wait for the real fix, since a quick eval of that
expression bombed "map" is the problem, supposed it needs to be
transient-map

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
that works:-)
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
I have added a key binding again but it is now `M-RET` for the reason given in commit d02b4f23e0371e4aae0ac4db5905d28878dad9a2.

**Comment by tvraman** [comment]
Thanks, but I must say that M-ret is not as usable as RET --- could you
also add C-RET?
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
I was considering that but since in some setups (i.e., in a console and without making an additional effort to undo this historic accident) there is no C-RET, since C-m is RET, and pressing both left and right Control won't give you C-C-RET.

Personally I have some magic going on that separates the return key from "pressing M while holding Control", but most users don't, so I don't think it would make sense to *only* bind C-return instead of M-RET. I also don't think that binding *both* is the right thing to do because each individual user would only use one of those bindings and adding the other binding just in case would mean needlessly overriding some other bindings outside of transient.

So I added a single default binding, M-RET, which should at least work for most users. Users for whom that doesn't work so well, such as you and me, will have to remove that binding and add their own binding instead. I went with `C-<return>`, maybe in your case it would make sense to use plain `RET` instead; there aren't really that many transient prefixes yet that support invoking non-suffixes anyway.
