### ISSUE TITLE
Transient Getting Slower With Magit?

### ISSUE THREAD

**Issue by tvraman** [magit/transient#205]
Description: Transient And Magit
Hard to measure, but when using Magit  commands like log, diff etc.,
i.e. those with fairly heavy-weight transients with many options,
things feel distinctly slower from what it used to feel like 6 months
ago. Is this true, or is it just me?

**Comment by tarsius** [comment]
I am on a mental health break (because all those little requests took a toll on me), but because I contacted you elsewhere, I'll make an exception and respond here.

Not that the answer is of much use: I think "it is just you". I haven't experienced any slowdown and cannot think of a possible cause due to recent changes. But I'll look at it again some time after returning from my break.

**Comment by tvraman** [comment]
Get well soon, Magit needs you:-)

I suspect the repeated levels of nesting and Emacspeak together are
slowing things down.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮
