### ISSUE TITLE
How to use transient programmatically?

### ISSUE THREAD

**Issue by djcb** [magit/transient#210]
This is more of a help-request than a feature-request per-se, but here it goes:

In mu4e, I have some way to ask the user for some option; i.e., I have something like:
```
(setq choices '(("Monkey" . monkey) ("Gnu" . gnu) ("xMoose" . moose)))
```
now, using `mu4e-read-option` , user can select one of those options by the first letter of `car`; it then evaluates to the corresponding `cdr`. So far so good.

I'm trying to (optionally) do the same with `transient`, but with my limited understanding of `transient`, I can get nothing closer than this monstrosity:

```
(defvar mu4e--options-result nil)
(defun mu4e-read-option-transient (prompt options)
  (let ((opts (vector
	       prompt
	       (apply #'vector
		      (seq-map
		       (lambda (option)
			 `(,(substring (car option) 0 1)
			   ,(car option)
			   (lambda () (interactive)
			     (setq mu4e--options-result (quote ,(cdr option))))))
		       options)))))
    (eval `(transient-define-prefix mu4e--option-transient nil ,prompt ,opts)))
    (setq mu4e--options-result nil)
   (funcall #'mu4e--option-transient)
    mu4e--options-result)

(mu4e-read-option-transient "Boo" choices)
```

This does not work; I expected the `funcall` to not return until the user has given their input. However, it returns immediately. 
Any hints how to do this instead? And can it be done without the `eva`l?

Thanks in advance for any hints.

**Comment by tarsius** [comment]
A few years ago I switched to `notmuch`, mostly due to peer pressure. Not sure that was the right choice; `mu4e` and now even `gnus` are still options I plan to investigate again. Anyway...

This looks similar to transients I have implemented in my [`notmuch-transient`](https://git.sr.ht/~tarsius/notmuch-transient) package. To build prefix with dynamic suffixes use the `:setup-children` property. `notmuch-search-transient` is a simple example, so start there, but I imagine you want to do something with tags, so `notmuch-tag-transient` is likely of interest too.

> I'm trying to (optionally) do the same with `transient`,

Having quickly looked at `mu4e-read-option` and its uses, I am not sure things are going to work so well, unless you are going all in. `transient` isn't structured in a way that makes it easy to write a drop-in replacement for a function like `mu4e-read-option`. You always need a prefix and at least one suffix, so it is already heavier than something based on `read-char-choice` or similar.

It's also not good at returning a value. The basic mode of operation is that a prefix sets a global value, which is consumed by the next command, much the same way prefix arguments work. I do plan to add support for returning values directly, but that will only allow a suffix (sub-prefix) to return a value to the (parent) prefix.

A function like `read-char-choice` can be called anywhere, while a transient "wants to be on the outside". Commands that currently use `mu4e-read-option` would likely have to be redefined to be transient prefixes, which take themselves as a suffix. Look at `magit-show-refs` for an example.

So while I think that `transient` would be a good match for `mu4e` and similar packages, I don't think it is a good fit for what you want just yet. One day I might add support for a `read-char-choice`-like workflow, but likely not soon and it might even turn out to not be feasible.

You can still play with transient now, but I recommend you start by completely rewriting one command to use transient to see how you like the result.

Also note, that I am taking a break from supporting users of my packages right now. I've made an exception here, but I expect that a lot more questions will come up when you look into this more, and answering them would require me to dive into `transient` myself and essentially turn my focus on that package for a while, and I don't want to do that.

Maybe it would be best if you shelved this project for a while, until I turn my focus back to transient. I am currently focused on tackling one thing at a time and bring that to completion, and currently that's not transient. At normal times I do tend to hop on things that users are struggling with, but that's the thing I am currently taking a break from.

**Comment by djcb** [comment]
Thank you for the detailed comments!

I've been using some simple `transients` in my emacs config for a while, to have nice menus, a bit like Hydra. I like the way it presents itself, so I thought that it'd be nice to use in in `mu4e` too (as an option, if `transient` is available). 

Indeed, ultimately `mu4e-read-option` is a fancy way to do a `read-char-exclusive`.  and I chose that function to apply `transient` to since it seemed like an easy way to make wide changes. But, thanks for explaining that's a bad match for what `transient` offers. I don't want to go "completely rewriting" things at this moment, since I also want to keep the old way in places for people who have older emacsen.

I'll take a look at `notmuch-transients`, there are some other places in mu4e where this might be a good fit. 

I'll close this then; enjoy your break :-).
