### ISSUE TITLE
Unwrapping a partial function in prefix stopped working with one of the newest transient versions

### ISSUE THREAD

**Issue by FieryCod** [magit/transient#224]
With one of the recent versions of `transient` unwrapping a partial function in `transient-define-prefix` stopped working.

```
(defvar transient-default-commands
  ["Transient"
   ("C-q"  "Quit"                 transient-quit-all)
   ("C-g"  "Quit to previous"     transient-quit-one)
   ("C-j"  "Scroll Down"          transient-scroll-down)
   ("C-k"  "Scroll Up"            transient-scroll-up)]
  "Default transient commands")
  
(defun +default/wrap-org-emphasize-renegotiate (emphasis-string)
  `(lambda ()
     (interactive)
     (if (not (region-active-p))
         nil
         ;; (+default/org-emphasize-word ,emphasis-string)
       (org-emphasize (if ,emphasis-string (string-to-char ,emphasis-string) nil)))))

(transient-define-prefix local-transient-org-emphasize-dashboard ()
  "Emphasize org mode text"
  [""
   [:class transient-row
           "Emphasize: "
           ("n" "Normal"        ,(+default/wrap-org-emphasize-renegotiate nil))
           ("b" "Bold"          ,(+default/wrap-org-emphasize-renegotiate "*"))]]
  transient-default-commands)
```

1. Previously transient allowed for injecting a partial function as a handler for a particular command.
    (1) I would expect the recent version of the transient to also honor this pattern.
    (2) Evaluating the snippet attached in the issue report results in: `transient--parse-suffix: Wrong type argument: stringp, (+default/wrap-org-emphasize-renegotiate nil) [1 times]`

Please include a backtrace in your report.  In most cases doing (I'm unable to gather the backtrace):

    M-x toggle-debug-on-error RET

and then going through the steps again should result in a backtrace.

Also, post the output of the following:

    M-x magit-version RET
    
```
Magit v3.3.0-475-g28d08627, Git 2.34.1, Emacs 29.0.50, gnu/linux
```

**Comment by tarsius** [comment]
I've added unquote in a misguided attempt to compile embedded lambda. I then added support to do something like https://github.com/magit/magit/commit/6ba3b50373fffa89ae99fc0ad5135e3d574f6df4. This was experimental and not documented.

Since ea851f3bde0b769b04ad03ab1a1341c013d0ddc6 lambda are automatically compiled without the need to unquote. I did keep support for unquote, but only following a keyword argument. This commit also added this note to the documentation (unquote is not otherwise mentioned):

> The value following a keyword, can be explicitly unquoted using `,`.
> This feature is experimental and should be avoided as well

I quickly tried if simply adding `:command` before the unquotes in your code would do the trick. It does not, the *positional* COMMAND argument is mandatory. So I additionally used `nil` as the value of that. That also does not work. At that point I gave up, because you shouldn't define anonymous suffix commands like this, even if doing so was possible.

Transient supports anonymous *infix* arguments but there is no support for anonymous *suffix* commands. If that worked before, this was only by accident. Suffix commands can be defined like any other command using `defun`. A benefit of that is that you can invoke such a command directly, even if you intend to usually invoke it from a transient.

```elisp
(defun my-org-emphasize-normal ()
  (interactive)
  (when (region-active-p)
    (org-emphasize nil)))

(defun my-org-emphasize-bold ()
  (interactive)
  (when (region-active-p)
    (org-emphasize ?*)))

(transient-define-prefix local-transient-org-emphasize-dashboard ()
  "Emphasize org mode text"
  [:class transient-row "Emphasize: "
   ("n" "Normal" my-org-emphasize-normal)
   ("b" "Bold"   my-org-emphasize-bold)])
```

I also would recommend against `:class transient-row "Emphasize: "`. Also you should not add `transient-default-commands` explicitly. They are always available after pressing `C-x`. If you want to always see them, set `transient-show-common-commands`.

**Comment by FieryCod** [comment]
Thank you so much @tarsius for the rationale. I'm specifying each command separately, now. All the best!

**Comment by tarsius** [comment]
You're welcome!

**Comment by FieryCod** [comment]
@tarsius btw, I'm using the following snippet to add some extra padding on top of the popup. Is it possible to add padding without this hack?

```
[""
   [:class transient-row]]
  
```

**Comment by tarsius** [comment]
No, there is not. (What you are doing is a bit of a hack, but I cannot think of a way to implement this "properly", which wouldn't be more verbose and less obvious.)

However, I noticed that you additionally put the "heading" on the left of the action row. If you stop doing both of those things, then you kinda get padding at the top (the heading being part of the padding).
