### ISSUE TITLE
Would you like to add the Version header?

### ISSUE THREAD

**Issue by TxGVNN** [magit/transient#238]
Hi Jonas Bernoulli,

By using Guix to install `transient`, they use `(lm-version "transient.el")` to build version into *-pkg.el file.
So the result is `0.0.0` in Emacs, it affects to the dependencies when installing.

src: https://git.savannah.gnu.org/cgit/guix.git/tree/guix/build/emacs-build-system.scm?h=5d10644371abd54d0edcd638691113f0a92de743#n189

More info: I suggested they use guix package version to apply to *-pkg.el, but no answer yet.

Regards!

**Comment by tarsius** [comment]
Would I *like* to include the version string in another place? No, I would prefer not having to check any version strings into Git at all, but I am forced to do it for some of my packages because they are on [Non]GNU Elpa, and they insist on getting version information from embedded version strings instead of from tags.

> I suggested they use guix package version to apply to *-pkg.el, but no answer yet.

IMO that was the right move and you will have to wait for them to respond. Please provide a link to the conversation/patch. I don't intend to chime in, but would like to read the response.

I switched to Guix too a few months ago, but use my own package manager, `borg`, to install Emacs packages. I do intend to start contributing to Emacs packages in Guix eventually, but I am not quite prepared to open that can of worms yet.
