### ISSUE TITLE
Transient treats a command as non-interactive

### ISSUE THREAD

**Issue by dpom** [magit/transient#240]
I implemented a simple UI for org-mode:
```
(require 'transient)
(transient-define-prefix local/org-menu ()
  "org menu"
  [["Edit1"
    ("'" "edit special" org-edit-special)
    ("-" "sort" org-sort)
    ("ed" "date" local/date-iso)
    ("c" "cycle bullets" org-cycle-list-bullet :transient t)
    ("ef" "footnote" org-footnote-action)
    ("eg" "tags" org-set-tags-command)
    ("eh" "heading" org-toggle-heading)]
   ["Edit2"
    ("ei" "item" org-toggle-item)
    ("el" "link" org-insert-link)
    ("ep" "property" org-set-property)
    ("et" "table of contents" org-make-toc-insert)
    ("eu" "update toc" org-make-toc)
    ("ew" "drawer" org-insert-drawer)
    ("ex" "id" org-id-get-create)]])
(evil-define-key '(normal visual motion) org-mode-map "\\" #'local/org-menu)
```
In practice, I noticed that the ```\el``` command behaves differently from the ```M-x org-insert-link``` command. The command does not display the Description prompt and exits immediately after inserting the link. Studying the code of the org-insert-link command, I saw that this behavior occurs when the function is not called interactively.
 Where did I go wrong in defining the command to be considered non-interactive?

**Comment by tarsius** [comment]
The command *is* called interactively. The problem is that `called-interactively-p` is not reliable, as described in its docstring:

> This function is very brittle, it may fail to return the intended result when
> the code is debugged, **advised**, or instrumented in some form.  Some macros and
> special forms (such as `condition-case`) may also sometimes wrap their bodies
> in a `lambda`, so any call to `called-interactively-p` from those bodies will
> indicate whether that lambda (rather than the surrounding function) was called
> interactively.
> 
> Instead of using this function, it is cleaner and more reliable to give your
> function an extra optional argument whose `interactive` spec specifies
> non-nil unconditionally (\"p\" is a good way to do this), or via
> (not (or executing-kbd-macro noninteractive)).

Unfortunately `transient` must **advise** the current command on the fly, see 51c68c87cc66322db2ee3d85b6f5fc8b941a2ed6.

If you run into such commands, you can either make its maintainer aware of the problem and ideally provide a patch to move away from `called-interactively-p`, or if that isn't feasible, you can use this ugly kludge:

```elisp
(transient-define-prefix local/org-menu ()
  "org menu"
  [("b" "link" (lambda ()
                 (interactive)
                 (call-interactively 'org-insert-link)))])
```

(I still have to purge `called-interactively-p` from my own code, not that I've used it a lot, but there are some instances.)

**Comment by dpom** [comment]
Thanks, @tarsius, indeed `org-insert-link` uses `called-interactively-p` and your "ugly kludge" solves the problem.
