### ISSUE TITLE
(void-function transient-prefix) in Emacs 29.1

### ISSUE THREAD

**Issue by jcs090218** [magit/transient#254]
I get this error every time I start a new Emacs session with the latest `transient` and Emacs 29.1.

```
Error loading autoloads: (void-function transient-prefix)
```

The error goes away after removing the latest transient from the `elpa` directory (replaced with built-in `transient`). 🤔

**Comment by tarsius** [comment]
That function has existed since the first commit. Maybe your elpa version was somehow corrupted. Try reinstalling and see if the issue returns.

**Comment by jcs090218** [comment]
That's the first thing I try, but no luck. FYI, I can reproduce it with `emacs -q` as well. It's a very strange error; I don't really know why. 🤔

**Comment by tarsius** [comment]
Maybe you installed a package that uses `transient` but doesn't autoload a call to `transient-define-prefix` or fails to require `transient`. If the problem is something along these lines, you can probably get around this by requiring `transient` very early in your init file. The version of `transient` that is in Emacs autoloads `transient-define-prefix`, the separately installed version does not, because last time I thought about it, I came to the conclusion that that wouldn't work in that case. I don't remember the details.

**Comment by jcs090218** [comment]
You are right. I need to require `transient` before `(package-initialize)` the problem goes away. It's quite annoying since I don't know which package is reporting the error. 😖 The error isn't from this package; therefore, I am closing it! 

Thank you for your help! 🙏 ❤️
