### ISSUE TITLE
display-buffer-in-child-frame for transient-display-buffer-action breaks

### ISSUE THREAD

**Issue by antifuchs** [magit/transient#27]
I tried setting `transient-display-buffer-action` to `display-buffer-in-child-frame` like so:

``` elisp
(setq transient-display-buffer-action '(display-buffer-in-child-frame)
```

With that form evaluated, transient will pop up in a child frame as expected, but doesn't accept any commands. The minibuffer is very confused and the child frame doesn't close down. (**WARNING**: This rendered my emacs session semi-broken and I had to quit it... with knowledge of transient internals, you may be able to repair the damage).

I'm not sure that I really *want* transients to appear in child frames, but I would expect them to not break emacs (:

**Comment by tarsius** [comment]
After skimming the "Child Frames" info node I think the behavior depends on the window manager. If the window manager selects the X11 window that corresponds to the child frame, then things break. `transient` assumes that the buffer from which the transient command was invoked remains the current buffer. If the window manager causes the child frame to be selected, then the buffer that displays the suffixes becomes the current buffer.

You will have to prevent that from happening, probably by wrapping `display-buffer-in-child-frame` to remember and restore the current/selected frame/window/buffer.

If you do that, then please contribute that function to `transient` with a doc-string that explains in more detail and with less speculation than above what the issue is and how it is solved.

I don't intend to work on this myself.

**Comment by tarsius** [comment]
By the way for me this didn't break the emacs session, I could still exit with `C-g`. But in addition to the wrong buffer being current, the child frame was also displayed in a very unfortunate location. You should probably also pass an argument to `display-buffer-in-child-frame` (resp. its wrapper) and document what values are useful and why.

**Comment by antifuchs** [comment]
Ah, seems this is more well-behaved on X than it is on macOS: There, transient keeps intercepting key presses. 

For example, I could not quit emacs normally because transient would intercept `C-x` (for `C-x C-c`); I also couldn't get it to stop doing that by pressing `C-g` or `ESC ESC ESC`.

**Comment by tarsius** [comment]
If you get this to work, then please add instructions to https://github.com/magit/transient/wiki/Tips-and-Tricks.
