### ISSUE TITLE
Use macro within transient definition

### ISSUE THREAD

**Issue by licht1stein** [magit/transient#284]
Hi,

I just probably cannot find it anywhere, but would it be possible to use a macro within transient definition? Here's the simplest example:

```elisp
(defmacro cmd (expr)
  '(lambda ()
     (interactive)
     ,expr))

(transient-define-prefix foo ()
  [["Test"
    ("c" "This is repo context" (cmd "foo"))
    ("b" "This is repo context" (lambda ()
                                  (interactive)
                                  (message "foo")))]])
```

I tried different variations of this, but I constantly get errors. This would allow defining repeating commands without boilerplate. For example I have a lot of this kind of commands:

```elisp
("d" "Sync deps" (lambda () (interactive) (cider-interactive-eval "(sync-deps)")))
```

A macro would allow me to make something like `("d" "Sync deps" (my-cider "(sync-deps)"))` which is each much easier to work with.

**Comment by tarsius** [comment]
A long time ago it would have been possible to do that using `,(cmd "foo")` (if I remember correctly), but I removed support for that. I have only used that for `,(lambda ...)`, never `,(something else)`. Use with a lambda was somewhat common though. After the change, those uses became simpler (and more importantly more "intuitive") because I added special handling; now one could use just `(lambda ...)`.

But the main reason for removing support for `,anything`, is that I came to the conclusion that using that feature was always a mistake, except for very simple lambda (and even then it is somewhat questionable).

What alternative should be used of course depends on the context. You have provided little of that, but I am guessing you want a bunch of commands that are essentially identical, but each one of them does something slightly different depending on the key that was used to invoke it.

Here is how you could do something similar (there's just one command):

```elisp
(defun foo ()
  (interactive)
  (message "%s" (oref (transient-suffix-object) description)))

(transient-define-prefix pfoo ()
  [["Test"
    ("c" "one" foo)
    ("b" "two" foo)]])
```

This uses the same command for both bindings and the two bindings do different things because they use the `description` slot of the suffix object associated with the pressed key.

Maybe reusing an existing suffix slot is not appropriate. Then you have to use your own slot, for which you have to add your own class:

```elisp
(defclass foo-suffix (transient-suffix)
  ((bar :initarg :bar)))

(defun foo ()
  (interactive)
  (message "%s" (oref (transient-suffix-object) bar)))

(transient-define-prefix pfoo ()
  [["Test"
    ("c" "one" foo :class foo-suffix :bar "ONE")
    ("b" "two" foo :class foo-suffix :bar "TWO")]])
```

----

Transient also support dynamically generated suffixes, like in this example:

```elisp
(transient-define-prefix notmuch-search-transient ()
  "Repeat a saved search.

Repeat a search, which is saved and associated
with a key in option `notmuch-saved-searches'.

This is a replacement for `notmuch-jump-search'."
  [:class transient-row
   :setup-children notmuch-search-transient--setup
   :description "Search"
   :pad-keys t]
  (interactive)
  (when (derived-mode-p 'notmuch-tree-mode)
    (notmuch-tree-close-message-window))
  (transient-setup 'notmuch-search-transient))

(defun notmuch-search-transient--setup (_)
  (transient-parse-suffixes
   'notmuch-search-transient
   (mapcar (lambda (search)
             (let-alist (notmuch-transient--plist-to-alist search)
               (and .key
                    (list (key-description .key)
                          .name
                          (lambda ()
                            (interactive)
                            (notmuch-transient--search
                             .search-type .query .sort-order))))))
           notmuch-saved-searches
           ;; Value is something like:
           ;; ((:name "inbox" :query "tag:inbox" :key "i")
           ;;  (:name "unread" :query "tag:unread" :key "u")
           ;;  (:name "flagged" :query "tag:flagged" :key "f")
           ;;  (:name "sent" :query "tag:sent" :key "t")
           ;;  (:name "drafts" :query "tag:draft" :key "d")
           ;;  (:name "all mail" :query "*" :key "a"))
           )))
```

If you use that approach, then you could call a macro, but doing the work directly in the lambda would probably make more sense.

----

By the way, I saw https://github.com/melpa/melpa/pull/9006 and assume this issue has something to do with that.

I am guessing that what you want to implement, is actually a way to dynamically turn a list of arbitrary commands and some associated metadata, into a prefix command. That sounds like a lot like the previous example.

----

Regarding that package, independent of this issue:

I'm not sure that adding yet another "registry for location dependent things" is the right move. It *might* be better to just use a `project-specific-commands` variable, that can be set in `.dir-locals-2.el`.

Likewise adding your own primitive mechanism for determining the project seems unfortunate; sooner or later a user will ask you to extend that. So I would recommend using an existing mechanism instead, e.g., the `project` package.

**Comment by licht1stein** [comment]
Thanks, I came to similar conclusions. Please take a look at the extendable version: https://github.com/licht1stein/context-transient.el

And also at the clojure specific solution:

https://github.com/licht1stein/context-transient.el#better-way-for-clojure

**Comment by tarsius** [comment]
> Here's the rewritten menu from above:

I think that's better.
