### ISSUE TITLE
Transient i18n/L10n Support

### ISSUE THREAD

**Issue by kickingvegas** [magit/transient#285]
Enhancement request to support localized strings to display for descriptions, docstrings, and other relevant documentation used by Transient.

Ask is motivated by language enhancement request for Casual https://github.com/kickingvegas/Casual/issues/140

**Comment by tarsius** [comment]
I don't think it is feasible to do that.

> for descriptions, docstrings

Docstrings isn't something that is specific to Transient, but is shared with Emacs and every package. So that would have to be implemented in Emacs. But after, what is it now, forty odd years, this still does not exist. So I would not hold my breath. Emacs' manuals have been translated to other languages, so it's not like we haven't realized that being able to use one's native language would be nice.

What would this look like? Maybe

```elisp
(defvar foo nil
  ((en "blabla.")
   (de "bläblä."))
```

but that would quickly make the source code unreadable. So maybe:

```elisp
(defvar foo nil
  "blabla.")

;; and in some "translation" file:
...
("blabla."
 (de "bläblä."))
...
```

Doing this for docstrings is way easier than for all the other strings that we would also want to translate. And not even that exists. `(format "bla %s bla" arg)` is already way harder. Also `blabla.` may appear in multiple places, in different packages, and might require a different translation in different places. So we would have to assign an identity to each string intended for human consumption. For docstrings this may be feasible.

```elisp
(defvar foo nil
  ("dwe823r3" "blabla."))
```

For the numerous strings that appear in code, including but not limited to transient definitions, I think this is simply not feasible.

I am sorry but I just don't see this happening.

**Comment by kickingvegas** [comment]
What about for just descriptions?

**Comment by tarsius** [comment]
> What about for just descriptions?

That's the *hardest* case. What is was trying to get at above is that I don't want to try to tackle the hardest case first, just because it is under my control/"responsibility", when the Emacs community as a whole has not managed to do it for the much simpler cases, despite a several decade head start.

- The shorter the string, the less unique. The descriptions in transients tend to be rather short. As a result we have to give up on the idea of having one central translation table that uses plain *string* as keys, and instead have to assign a unique identifier to each string and use that as the key.
- Assigning a unique identifier to a docstring, doesn't make the respective function/variable/... *that* much uglier, but for numerous strings in a complex data structure such as a transient prefix definition, this would make it all but unreadable.
- Suffix descriptions do not have to be static strings. They can be generated dynamically using state into account, using arbitrary functions.
- ...

Attempting to do this (while trying to maintain some style and general readability) would occupy me for several months/years, suck all the fun out of it, and mean all other progress would crawl to a halt. I don't think this is what I should be focusing on.

Transient is already rather complex as it is. I do not want to add this complexity *multiplier*.

**Comment by tarsius** [comment]
Likewise I don't think you should merge the mentioned pull-request. Maintaining that is just not feasible either. What I would suggest instead, is that highly motivated translators, maintain each translation as a patch that they regularly rebase on top of `origin/master`. That patch would change all the descriptions in place. No tooling, functionality and special skills required, beyond fluency in both languages and conflict resolution.

I think this is the only feasible approach. However I doubt it will happen because it would require a large commitment from the translator, which goes beyond "just translating all the strings once" approach they likely would prefer.

Like you seem to drastically underestimate the effort it would take me to support this in a generic fashion, the translator underestimate the effort it would take to maintain translations in the absence of built-in support. If we want translations, someone has to do the work beyond the initial translation effort. I can understand that you want to offload that to me, and that the translator wants to offload it to you, and that they want the ui to be translated in the first place. But I don't think either one of us can be expected to do that work on top of (or rather instead of) all the other work we do.

**Comment by kickingvegas** [comment]
@tarsius TBH, I realize that this enhancement request is a **big** ask. Rather than being prescriptive though I thought it best to just ask directly. I do appreciate your feedback and the challenge it is to even consider adding L10n/i18n to Emacs and Transient as it was never designed in from the start.

I do wonder though if your assertion that for descriptions, one must abandon the notion of having a central translation table. A counter-argument is that such an implementation might be “good enough” to effectively communicate intent. I’m currently mulling over what that could look like from the points of view of the user, translator, and developer.

Agreed that the aforementioned pull request is not a desirable course to take and have rejected it.

While I do understand your reluctance to tackle this issue, I do think that Transient does provide the opportunity to revisit Emacs UI, particularly with regards to L10n/i18n with a fresh perspective. Perhaps this is worth considering.

**Comment by tarsius** [comment]
> A counter-argument is that such an implementation might be “good enough” to effectively communicate intent.

Maybe. :grimacing:

> I’m currently mulling over what that could look like from the points of view of the user, translator, and developer.

An `transient-format-description` :around method might be enough for a minimal viable implementation.

**Comment by kickingvegas** [comment]
How would `transient-format-description` `:around` work?

**Comment by tarsius** [comment]
There already is an around method, so this won't actually be possible. I recommend that for now you modify that method (`transient-format-description :around ((obj transient-suffix))`). Iff and once you have implemented a sufficiently useful translation mechanism, I could add a hook to that method, to allow you to hook up things without having to modify `transient.el`.

**Comment by tarsius** [comment]
I might later implement such a hook and push it to a feature branch.

**Comment by tarsius** [comment]
I have pushed something to the `translate` branch. It's completely untested. You might have to inject `transient--maybe-translate` in additional places, and maybe you have to move the current calls.

**Comment by kickingvegas** [comment]
Interesting. Have a better understanding of your intent to modify `transient-format-description` to transparently handle the translation. That said, my thinking on localization is much more influenced from developing for Apple APIs. The pattern is to have a dedicated function to localize the string (in this case [NSLocalizedString](https://developer.apple.com/documentation/foundation/nslocalizedstring)). This function would then infer from a system setting the locale and then do the mapping to a localized value if it exists, otherwise it puts in the key (in this case the original string text, which we can treat as English by default since it is already that way in Emacs). Another benefit is that this obviates the need to modify `transient-format-description`. A proposed new function `(transient-localized-string KEY)` would do the heavy lifting, also enforcing conventions for defining the translation catalog. Its result would be passed to `:description`. The initial implementation of `transient-format-description` could be naive in that it is just does a simple mapping and avoids corner cases like handling plurals and quantities. The language configuration could be done via a proposed customizable variable `transient-lang` which could be initialized by the shell environment `LANG` variable.

While the above approach necessitates annotating each string to be localized, I think this is a feature because it makes the intent explicit to the developer. Existing Transient code doesn’t break and the weight is on `transient-localized-string` to do the right thing. The one unknown I have is performance, but even then, the translation catalog might in practice be relatively small so it would make little difference.

**Comment by tarsius** [comment]
Do I understand you correctly, you want to do this?:

```diff
-("A" "Apply"          magit-cherry-pick)
+("A" (transient-localized-string "Apply" 123)          magit-cherry-pick)
```

If so, here is a variation that would decrease readability less massively:

```diff
-("A" "Apply"          magit-cherry-pick)
+("A" "Apply"          magit-cherry-pick :loc-id 123)
```

The above you could already do now, but it would be even uglier:

```diff
-("A" "Apply"          magit-cherry-pick)
+("A" (lambda () (transient-localized-string "Apply" 123))          magit-cherry-pick)
```

I plan to add support for my [`##` macro](https://git.sr.ht/~tarsius/llama) soonish. Once that is done, you could use:

```diff
-("A" "Apply"          magit-cherry-pick)
+("A" (##transient-localized-string "Apply" 123)          magit-cherry-pick)
```

However all this IMO is not necessary. This works too:

```elisp
(setq transient-translation-function
      (lambda (string suffix-object)
        (gethash (list (oref transient--prefix command)
                       (oref suffix-object command)
                       string
                       ;; ^- This is all but guaranteed to be an unique key.
                       ;; v- Add the language to that.
                       'chinese)
                 translation-table)))
```

But I might be willing to implement support for some special syntax, along what you are suggesting. Without thinking too much about it, this seems reasonable:

```diff
-("A" "Apply"          magit-cherry-pick)
+("A" ["Apply"123]          magit-cherry-pick)
```

This would then be expanded to code along the lines of the above `(transient-localized-string "Apply" 123)`.

However, I am really busy, so I don't intend to work on any of this before June at the earliest.
