### ISSUE TITLE
Emacs considers it an error to use variables in a prefix as groups when defined in the same package

### ISSUE THREAD

**Issue by aurtzy** [magit/transient#331]
## Info

System: Guix System

Emacs version: `GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)`

Transient version: d64b73efbc0615eaa58f15f8a0438a2c010f5682

Tested with `emacs -Q`.

## Problem

Emacs considers it an error for `transient-define-prefix` to use a variable/constant as a group when it is defined in the same package.

## Expected behavior

For variables defined in the same package as a prefix to be valid when used in the prefix definition.

## Reproduction steps

1.  Create two files `test.el` and `test-consts.el` under the same directory with the corresponding snippets below.
2.  Add the directory where the files are to the load path; I evaluate `(add-to-list 'load-path (expand-file-name "."))` in the `test.el` file.
3.  Enable `flymake-mode` in `test.el`.  See that no errors are indicated.
4.  Change the reference from `test-okay-group` to `test-bad-group` in the `test-prefix` definition and save the file.  See that there is now the following error:
    
    > Symbol's value as variable is void: test-bad-group

Notably, the prefix definition still works as expected when evaluating the file either way e.g. with `C-c C-e`.

`test.el`:

```emacs-lisp
(require 'transient)
(require 'test-consts)

(defconst test-bad-group ["Test commands" ("f" "Find a file" find-file)])

(transient-define-prefix test-prefix ()
  test-okay-group)

(provide 'test)
```

`test-consts.el`:

```emacs-lisp
(defconst test-okay-group ["Test commands" ("f" "Find a file" find-file)])
(provide 'test-consts)
```

**Comment by tarsius** [comment]
This (when using the "bad" group) compiles and can be loaded (whether compiled or not) without any errors or warnings.

It's just flymake that is getting confused about it.

You can help flymake get over its false-positive by wrapping the `defconst` in `eval-and-compile`. (Note that the description of this macro in the manual is much better than its doc-string.)

The reason flymake gets confused might be due to countermeasures for the kind of issue described in https://eshelyaron.com/posts/2024-11-27-emacs-aritrary-code-execution-and-how-to-avoid-it.html.
