### ISSUE TITLE
Arrow keys don't work to navigate magit popup

### ISSUE THREAD

**Issue by bhollis** [magit/transient#38]
I'm having trouble since recently updating magit - I can no longer use arrow keys to navigate inside magit's popups. When I do, I get errors like `Unbound suffix: ‘<down>’ (Use ‘C-g’ to abort, ‘?’ for help)`. I've tried `magit-emacs-Q-command` and even then it doesn't work. Any tips on how to reenable arrow key navigation?

The q-command has the versions of my dependencies:
```
/usr/local/Cellar/emacs-plus/26.1/Emacs.app/Contents/MacOS/Emacs -Q --eval \(setq\ debug-on-error\ t\) -L $HOME/.emacs.d/elpa/dash-20190413.1058/ -L $HOME/elpa/transient-20190419.2124/ -L $HOME/.emacs.d/elpa/with-editor-20190224.931/ -L $HOME/.emacs.d/elpa/magit-20190420.1907/ -L $HOME/.emacs.d/elpa/git-commit-20190413.1201/ -l $HOME/.emacs.d/elpa/magit-20190420.1907/magit`

**Comment by kyleam** [comment]
This was touched on in #17, where Jonas [said], "Isearch and selecting a suffix using the arrow keys or the mouse is still not possible again. Not sure if I want to bring that back."

[said]: https://github.com/magit/transient/issues/17#issuecomment-468423922

**Comment by bhollis** [comment]
That's unfortunate. It was really quick to be able to do that. I also hadn't ever learned that I could select the options by typing `-` and the letter. It's good to know that I can, but my muscle memory is still to just tap the arrow keys once or twice to find the option I'm looking for.

**Comment by return42** [comment]
Sorry for being ignorant, but I don't see the benefit of modal (transient) dialogs (for me). I have been using the emacs for 30 years and have never (consciously) perceived a modal dialogue. I like to be the master of any buffer, navigating with up/down arrow keys and using incremental search. Now I feel like in a jail, that is what I know from other IDE, not from emacs.

Is there a way to disable such modal dialogs?

**Comment by return42** [comment]
Another point with transient, long know keystrokes no longer work (e.g `C-c C-`is now `C-x C-s`) .. phew!

**Comment by tarsius** [comment]
I was actually just about to start working on bringing back arrow navigation...

> have never (consciously) perceived a modal dialogue

Please read this first: https://github.com/magit/transient/issues/17#issuecomment-464243333.

In summary. Transient popups are like incomplete key sequences. You can only invoke commands that are available given the current incomplete key sequence or abort. One could call that a modal interface. Transient differs from regular prefix keys in that it shows you the available suffixes in a buffer. That causes it to be perceived as more modal, but really it is exactly the same as for regular incomplete key sequences except for the visual feedback.

Additionally note the explanations about the popup buffer not being the `current-buffer` and why that is useful.

> Is there a way to disable such modal dialogs?

You can set `transient-show-popup` to `nil`. This prevents the popup from being shown. Instead you get something like this in the echo area:

```
c- [magit-commit] -A|-C|-R|-a|-e|-n|-s|-v|A|F|S|a|c|e|f|n|s|w|x
```

You can also set it to `0` in which case you see only:

```
c-
```

I.e. the transient then behaves exactly like a regular prefix command. Well almost, if you press `-` then the popup is shown. If that were not the case, then you wouldn't be able to know whether then pressing `a` enables or disables the `--all` argument.

----

All that being said I do take these concerns seriously. I just want users to know why I have done things the way I have and that it enables features that would otherwise not be possible.

So I am going to bring back some functionality that was lost due to Transient being more modal but without making it less modal. I still think that whether it should be considered more modal is a matter of perception, but if that's your perception, then I won't deny you that. :wink:

**Comment by tarsius** [comment]
> Another point with transient, long know keystrokes do no longer work (e.g `C-c C-c`is now `C-x C-s`) .. phew!

The rational is explained here: https://magit.vc/manual/transient/FAQ.html#Why-did-some-of-the-key-bindings-change_003f.

**Comment by return42** [comment]
@tarsius thanks for your feedback.  I have read the docs you linked but I have a doubt that I have understood all in deep ;)  I really will give it a try. ATM it is hard for me to change my keystrokes that flow out of my fingers routinely without me ever thinking about it.

> I still think that whether it should be considered more modal is a matter of perception ...

Since I can't change to any other buffer. Anyway, thanks for all your work on magit-popup and transient!

**Comment by tarsius** [comment]
Arrow key navigation, mouse support, and isearch support have been restored. You need to set an option to enable these features. See #42.
