### ISSUE TITLE
Getting a return value from a transient

### ISSUE THREAD

**Issue by TinaRussell** [magit/transient#59]
I know transients were invented to make it easier to use external commands, but I’d like to use them to grab some quick data from the user. But, I can’t get a transient to return anything. For instance:
```
(defun tinas-suffix ()
  (interactive)
  42)

(define-transient-command tinas-transient
  "An example transient"
  ["Tina’s transient"
   ("t" "Tina’s suffix" tinas-suffix)])

(setq test-var (tinas-transient))
test-var
```
`test-var`, at the end, is nil, not 42. I can even try something more elaborate:
```
(defvar rtn-var nil)

(defun tinas-suffix ()
  (interactive)
  (setq rtn-var 42))

(define-transient-command tinas-transient
  "An example transient"
  ["Tina’s transient"
   ("t" "Tina’s suffix" tinas-suffix)])

(defun tinas-transient-wrapper ()
  (interactive)
  (setq rtn-var nil)
  (tinas-transient)
  (prog1 rtn-var
    (setq rtn-var nil)))

(setq test-var (tinas-transient-wrapper))
test-var
```
…and `test-var` is still nil. (Further testing shows that the end of `tinas-transient-wrapper` is being run /before/ the code in `tinas-suffix`, hence why it’s so difficult to get a synchronous return value.)

What am I doing wrong?

**Comment by tarsius** [comment]
Using transients as some sort of `read-char-choice` replacement is not possible. At least not without restructuring the code fundamentally. You would have to move the code that "consumes" the value into each suffix instead of placing it inside a wrapper around the prefix. I recommend you use `read-char-choice`, possibly writing your own wrapper around that and make it display the choices similar to `transient` does it.

A transient prefix commands just changes global state, it doesn't actually "do" anything. Basically it merely sets up a few keymaps and displays the popup buffer. The latter it doesn't even do itself--it adds a function to `post-command-hook`, which then later does it. If called interactively the prefix command then returns to the command-loop, `post-command-hook` is run, and finally the user may press keys to invoke another command (in most cases [s]he is now restricted to suffix commands).

If the transient prefix command is called non-interactively, then it returns to where it was called from and the caller continues as usual (without waiting for user-input). Only once the current command is done do we return to the command loop and the user has a chance to invoke a suffix.

Transients do *not* use "recursive editing".
