### ISSUE TITLE
popup navigation in no window mode

### ISSUE THREAD

**Issue by flagos** [magit/transient#60]
Hi,

When launching emacs in emacs -nw with the popup navigation option introduced in #42, I cannot navigate with key arrows. In normal mode (with a window) it's working as expected.

Am I the only one to face the issue ?

**Comment by tarsius** [comment]
At least for me, the key bindings work correctly. I do not get any warnings about the arrow keys being unbound suffixes. However there is no visual indicator of there the point is in the popup buffer, which makes this kinda useless. In the commit popup if I type <kbd>down down RET<kbd>, then that toggles the third option, `--verbose`, as expected.

So the question is why the cursor is not being displayed despite `cursor-in-non-selected-windows` being `t`. In GUI Emacs this setting is respected, just not in terminal. So its not really a Transient question, but if you figure this out, then I would still like hear about the solution.

**Comment by flagos** [comment]
Indeed I didn't notice the problem is just about the cursor and having a visual feedback.

Waiting if anyone reading here could have a suggestion, feel free to close it if you consider there is not much of interest of having it open.

**Comment by tarsius** [comment]
It appears this is because Emacs doesn't draw the cursor(s) itself; instead it asks the terminal to do so. The terminal only has a concept of a single cursor. See [Displaying the Cursor](https://www.gnu.org/software/emacs/manual/html_node/emacs/Cursor-Display.html).

Theoretically Emacs could be taught to draw the cursors itself. If you want that, then you'll have to take it up with the Emacs developers.
