### ISSUE TITLE
Transient buffer does not adjust to custom `transient-mode-line-format`.

### ISSUE THREAD

**Issue by jjzmajic** [magit/transient#63]
When a custom `transient-mode-line-format` is set, the height of the buffer is not recomputed based on it, so if the mode-line is too wide, it covers some bindings in the pop-up.

**Comment by tarsius** [comment]
Please provide a recipe to reproduce this starting from `emacs -Q`. See https://magit.vc/manual/magit/Debugging-Tools.html.

**Comment by tarsius** [comment]
Also try if this makes a difference:

```diff
diff --git a/lisp/transient.el b/lisp/transient.el
index 731fe6a..686a76a 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -2455,6 +2455,10 @@ (defun transient--show ()
   (setq transient--showp t)
   (let ((buf (get-buffer-create transient--buffer-name))
         (focus nil))
+    (with-current-buffer buf
+      (setq mode-line-format (if (eq transient-mode-line-format 'line)
+                                 nil
+                               transient-mode-line-format)))
     (unless (window-live-p transient--window)
       (setq transient--window
             (display-buffer buf transient-display-buffer-action)))
@@ -2468,9 +2472,6 @@ (defun transient--show ()
       (setq window-size-fixed t)
       (when (bound-and-true-p tab-line-format)
         (setq tab-line-format nil))
-      (setq mode-line-format (if (eq transient-mode-line-format 'line)
-                                 nil
-                               transient-mode-line-format))
       (setq mode-line-buffer-identification
             (symbol-name (oref transient--prefix command)))
       (if transient-enable-popup-navigation

```

**Comment by jjzmajic** [comment]
Spot on sir, that fixes it.

**Comment by jjzmajic** [comment]
Correction, it appears not to fix it completely. here's the reproducible example after `emacs -Q`:

```elisp
;; add to load path, I use straight.el so it's not useful here
(require 'doom-modeline)
(require 'magit)
(setq transient-mode-line-format
          (doom-modeline 'minimal))
```

- Navigate to repo and `M-x magit-status`
- `M-x magit-dispatch`
- Note that parts of "Essential commands" are cut off, sometimes by half a line, sometimes entire entries (depending on window size) 
- This is fixed by hitting `<escape>` or any other key not in the transient map

**Comment by tarsius** [comment]
This worked for me:

```diff
diff --git a/lisp/transient.el b/lisp/transient.el
index 731fe6a..b9eddf3 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -2487,6 +2487,7 @@ (defun transient--show ()
         (insert (propertize "\n" 'face 'transient-separator 'line-height t)))
       (let ((window-resize-pixelwise t)
             (window-size-fixed nil))
+        (redisplay t)
         (fit-window-to-buffer nil nil 1))
       (goto-char (point-min))
       (when transient-enable-popup-navigation
```

I am also the author of `moody`, a competitor to `doom-modeline`, and just dealt with a similar issue "from the other perspective". The issue is https://github.com/tarsius/moody/issues/19 and the work-around with a description of the issue is https://github.com/tarsius/moody/commit/d37945b3a4c6ea5560eaf15f39d98aa23537d70c.

`doom-modeline` should arguably do the same thing. /cc @seagle0128

Please try the simple work-around I have suggested above and report if it works. Even if it does, I still don't think I should add that. The issue really is with Emacs for using incorrect values until being forced to calculate the correct values.

That issue does not matter until something actually changes the height of the mode-line. I therefore think that packages that change the height (e.g. `moody` and `doom-modeline`) are responsible for triggering the calculation when necessary. (Calling `redisplay` *should* be unnecessary and doing so anyway *just in case* would therefore be *wasteful*, expect when it actually is necessary and that is so when one of these packages is used.)

**Comment by seagle0128** [comment]
Yep, there are similar issues reported in `doom-modeline`.

e.g. https://github.com/seagle0128/doom-modeline/issues/183

Thank you for the information!

**Comment by tarsius** [comment]
@seagle0128 I ended up having to add https://github.com/tarsius/moody/commits/master to prevent transient popups from flashing weirdly.

**Comment by tarsius** [comment]
In the end what we really need is for Emacs to realize that it has to calculate the height of the mode-line when appropriate. Eventually I will probably get around to discussing that with the Emacs developers but I certainly wouldn't mind if someone else took that upon them...

**Comment by jjzmajic** [comment]
Sending via mail...
Sending...done
