### ISSUE TITLE
Show warnings when define transient-command with duplicate suffix

### ISSUE THREAD

**Issue by conao3** [magit/transient#71]
Hi!
This snippet define transient-command named `tmp` but definition include suffix duplicate.
```emacs-lisp
(define-transient-command tmp ()
  "tmp"
  ["tmp"
   ("a" "Add"    magit-commit-amend)
   ;; ...
   ("a" "ingore" ignore)
   ;; ...
   ])
```

I invoke `tmp` as interactively, type `a`, just run `ignore` command.
It seems to overwrite by the latter specification.
This is hard to detect manually if transient command is too long, please show warnings if there're duplicate suffix like a using non-defined function.
(Debugger entered--Lisp error: (error #("Suffix ignoree is not defined or autoloaded as a command")))

**Comment by tarsius** [comment]
> It seems to overwrite by the latter specification.

IMO that's okay because `define-key` does the same.

> This is hard to detect manually

I agree and that's why I have added `transient-detect-key-conflicts`, which you have to set to `t`. The conflict is reported when the transient is invoked, not when the transient is defined or gets extended. That's why it is opt-in--the transient should continue to work for regular users (except for one of the two conflicting bindings).

**Comment by conao3** [comment]
OK, and thanks for letting me know `transient-detect-key-conflicts`.
